### PR TITLE
Add x-path query and settings panel to uast viewer pane

### PR DESCRIPTION
**Pull request by smacker**
Fix: #127

screen shot 2018-06-21 at 16 04 39

### CODE REVIEW

**Comment by smacker** [comment]
I think it's product decision, not my. Do we want filtering on code & uast modals now or do we want wait?
Uast filtering on another modal depends on this PR.

**Comment by smacker** [comment]
Rebased on master. Rebase was hard and commit history didn't make sense anymore. So I squshed commits.

**Comment by bzz** [comment]
👍  \cc @carlosms for a review

**Comment by carlosms** [comment]
I see the following problem. The `CodeViewer.state.filter` acts as a global setting, persistent between different modals (different rows). But visually the checkbox does not follow this setting.

To reproduce:
- open a CODE viewer for one row
- set a custom bblfsh url
- close this modal
- open modal for other row

Now the new modal will use the bblfsh url set previously, but the "custom server" checkbox is unchecked.

I would also use  `127.0.0.1:9432` instead of `0.0.0.0:9432`.

**Comment by smacker** [comment]
thanks for reporting. side effect after rebase. I'll fix it.

**Comment by smacker** [comment]
Fixed.

I use `0.0.0.0:9432` because dashboard uses it.

**Pull request merged**
