### PR TITLE
add help link

### PR DESCRIPTION
**Pull request by smacker**
Fix: #103

It might look a bit strange when the first line of query is too long but I don't see how to make it better (from UI point of view).

screen shot 2018-06-28 at 16 51 02

### CODE REVIEW

**Comment by carlosms** [comment]
I think that having that text hidden behind the button makes it look like something is a bit broken.

What do you think about shrinking the codemirror area, like this image? It will look the same with small queries that don't overflow.

image

**Comment by smacker** [comment]
TBH I think it looks super ugly. Worse than hidden text.

@ricardobaeta could we have your input here? I don't think it's possible to make the text go around that button due to codemirror. So most probably we have only this 2 options as on my screenshot and as on Carlos screenshot.

**Comment by ricardobaeta** [comment]
@carlosms @smacker 

Relying on the query input field scroll that we have, I propose just to give background: #fff to the container of the "HELP" element. With some nice padding.

**Comment by smacker** [comment]
didn't get the idea. The original PR has `#fff` background. @carlosms maybe we should merge it then and let Ricardo fix it in browser?

**Comment by ricardobaeta** [comment]
@smacker I like @carlosms suggestion. If we could have the padding a fill with gradient from #fff opaque and #fff transparent it would be a nice detail I think.

**Comment by smacker** [comment]
sorry I still don't understand like at all :( gradient into the textarea with scroll? or how?

**Comment by smacker** [comment]
got it.

Current look:
screen shot 2018-07-02 at 13 03 17

**Comment by ricardobaeta** [comment]
Hi @smacker !

Nicely done ;)

**Comment by carlosms** [comment]
Leaving aside my conviction that this looks like a bug instead of an intended design, I see a problem when I hover the icon. I guess the background should still be white to avoid the weird mix of texts.

a

**Comment by smacker** [comment]
fixed hover

**Comment by ricardobaeta** [comment]
Hi @carlosms!

You spotted a very nice detail, thank you ✨ 

I presume @smacker maintained the background on :hover, and I like it. For me it's fine.

Just food for thought:

image

**Pull request merged**
