### PR TITLE
Detect lang endpoint

### PR DESCRIPTION
**Pull request by smacker**
As discussed we need such endpoint. There is a problem that enry can't detect language without filename in most cases. So I'm not sure we need to merge it now. But in case we need.

### CODE REVIEW

**Comment by bzz** [comment]
> As discussed we need such endpoint

Just for the context, we need it for 2 reasons
 - Code -> UAST, for request to bblfsh
 - Syntax hightligh for CodeMirror

**Comment by bzz** [comment]
@smacker how about handling the case of detecting a language only by content as well?

**Comment by smacker** [comment]
@bzz you can see in tests you can pass empty filename and enry will try to guess it by content only https://github.com/src-d/gitbase-playground/pull/85/files#diff-bbb690ba3ea1b1821225ad2e890527c9R35

**Comment by smacker** [comment]
There is no any custom logic. It's just HTTP proxy to enry.
Documentation of enry doesn't mention it as a special use-case: https://godoc.org/gopkg.in/src-d/enry.v1#GetLanguage

**Pull request merged**
